Repository The-Bugger-Ducks/mood-hound-back, pull requests merged in 2023-10, with the labels that each got.

#31 Fix/rename documents fields
  src/domain/abstractions/generic-repository.abstract.ts
  src/domain/entities/comment.entity.ts
  src/domain/entities/index.ts
  src/domain/entities/user.entity.ts
  src/shared/database/implementations/comment.repository.impl.ts
  src/shared/database/implementations/user.repository.impl.ts
Labels: bug

#30 Feat/#25 comments per state
  src/domain/repositories/comment.repository.ts
  src/modules/dashboard/dashboard.service.ts
  src/shared/database/implementations/comment.repository.impl.ts
Labels: feature request, p.o approval, pull request, back

#33 Feat/unit tests mongo
  .eslintrc.js
  .github/workflows/sonarcloud.yml
  .prettierrc
  jest.config.mjs
  package.json
  sonar-project.properties
  src/domain/dtos/comment/create.comment.dto.ts
  src/domain/dtos/comment/filter.comment.dto.ts
  src/domain/dtos/user/create.user.dto.ts
  src/domain/dtos/user/update.userRole.dto.ts
  src/domain/repositories/comment.repository.ts
  src/domain/repositories/user.repository.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/comments/comments.controller.ts
  src/modules/comments/comments.module.ts
  src/modules/comments/comments.service.ts
  src/modules/dashboard/dashboard.module.ts
  src/modules/dashboard/dashboard.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  src/shared/database/implementations/comment.repository.impl.ts
  src/shared/database/implementations/user.repository.impl.ts
  src/shared/database/seeds/user.seed.ts
  src/shared/database/services/database.service.ts
  src/shared/decorators/HasRoles.decorator.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  test/users/user.controller.spec.ts
  test/utils/mongo.utils.spec.ts
  tsconfig.json
Labels: back

#35 feat: filter dashboard
  src/domain/dtos/dashboard/filter.dashboard.dto.ts
  src/domain/dtos/index.ts
  src/domain/entities/comment.entity.ts
  src/domain/repositories/comment.repository.ts
  src/modules/dashboard/dashboard.controller.ts
  src/modules/dashboard/dashboard.service.ts
  src/shared/database/implementations/comment.repository.impl.ts
Labels: back

#36 Fix/sonar issues
  src/domain/dtos/user/create.user.dto.ts
  src/shared/database/seeds/user.seed.ts
Labels: back

#32 Development
  .eslintrc.js
  .github/workflows/sonarcloud.yml
  .prettierrc
  jest.config.mjs
  package.json
  prisma/schema.prisma
  sonar-project.properties
  src/app.module.ts
  src/domain/abstractions/data-services.abstract.ts
  src/domain/abstractions/generic-repository.abstract.ts
  src/domain/abstractions/index.ts
  src/domain/dtos/comment/create.comment.dto.ts
  src/domain/dtos/comment/filter.comment.dto.ts
  src/domain/dtos/dashboard/filter.dashboard.dto.ts
  src/domain/dtos/index.ts
  src/domain/dtos/user/create.user.dto.ts
  src/domain/dtos/user/update.user.dto.ts
  src/domain/dtos/user/update.userRole.dto.ts
  src/domain/entities/comment.entity.ts
  src/domain/entities/index.ts
  src/domain/entities/user.entity.ts
  src/domain/repositories/comment.repository.ts
  src/domain/repositories/index.ts
  src/domain/repositories/user.repository.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/comments/comments.controller.ts
  src/modules/comments/comments.module.ts
  src/modules/comments/comments.service.ts
  src/modules/comments/entities/comment.entity.ts
  src/modules/dashboard/dashboard.controller.ts
  src/modules/dashboard/dashboard.module.ts
  src/modules/dashboard/dashboard.service.ts
  src/modules/users/entities/users.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  src/shared/config/env.ts
  src/shared/database/database.module.ts
  src/shared/database/implementations/comment.repository.impl.ts
  src/shared/database/implementations/index.ts
  src/shared/database/implementations/user.repository.impl.ts
  src/shared/database/prisma.service.ts
  src/shared/database/repositories/comments.repositories.ts
  src/shared/database/repositories/users.repositories.ts
  src/shared/database/seeds/user.seed.ts
  src/shared/database/services/database.service.ts
  src/shared/decorators/HasRoles.decorator.ts
  src/shared/pipes/ParseObjectIDPipe.ts
  src/shared/utils/Mongo.util.ts
  src/shared/utils/paginator/pageMeta.dto.ts
  src/shared/utils/paginator/pageOptions.dto.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  test/users/user.controller.spec.ts
  test/utils/mongo.utils.spec.ts
  tsconfig.json
  yarn.lock
Labels: back
